### PR TITLE
2016jan

### PR DESCRIPTION
**Pull request by jmackereth**
I have now added Simulation and Halo object classes to the code. see the readme for details. The code still also works in the original way, as we edited it on the 26/01/16, however:

to slim down on memory usage i have added a new option to the loadparticles function. The mass_cut option is a tradeoff between preselecting haloes and having the whole lot. You put in a tuple, such as [4e10, 9e10] and the function will then only return particles from centrals with masses in that range (in units of M_sun, naturally). This way you can open the simulations even when there is limited memory available (as little as 5GB). 

Let me know if theres any problems?

### CODE REVIEW

**Comment by Samwalton9** [comment]
That makes a lot of sense! Is that in stellar mass or total mass?

**Comment by jmackereth** [comment]
sorry, stellar mass!

works quite nicely i think!

also how annoying is it that GitHub doesn’t count this as a contribution because i removed more lines than i added haha!

**Comment by Samwalton9** [comment]
Ha. It also looks like we can't merge it like normal... Not sure how we say 'screw what was there before, just write over it'.

**Comment by jmackereth** [comment]
i think you can do some sort of forced merge using the command line, ill have a look, for now maybe its a good idea to just checkout the 2016jan branch, I’m not sure..

**Comment by Samwalton9** [comment]
That makes sense, yeah.

Given that loadparticles now has maaaany less galaxies, it might make sense for halo to just go through all of them in one go?

**Comment by jmackereth** [comment]
It depends, you can use it however you need now. We should ask about making a shared folder in /data5 for our common data though.

**Comment by Samwalton9** [comment]
Yeah. Can we just do that anyway, or is it set up to only allow us to make individual directories?

**Comment by jmackereth** [comment]
im not sure, but all we would have to do is adjust the work_dir variable in the code.

in fact, if you write a script i think you can just use
et.work_dir = ‘whatever/directory’

after the import command, and you don’t need to adjust the source code.

**Comment by Samwalton9** [comment]
Nifty.

**Pull request merged**
